version: '3.8'
services:
  api:
    build: .
    image: airbus_duc # image name
    container_name: airbus_duc_con # container name
    volumes:
      - airbus_data:/workspace/data
    ports:
      - 8080:8080
    shm_size: '11gb'  # set the shared memory size to 2GB
    ulimits:
      memlock: # unlimited
        soft: -1 
        hard: -1
      stack: 67108864 # stack size limit
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    
volumes:
  airbus_data:
    external: true