_target_: src.models.mask_rcnn.mask_rcnn_module.MaskRCNNLitModule
defaults:
  - net: mask_rcnn.yaml

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.0001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10
