_target_: src.models.MultiClassUnet.MultiClassUnet_module.MultiClassUnetLitModule
defaults:
  - criterion: lovasz_softmax_loss.yaml
  - net: MultiClassUnet34.yaml

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 5
