_target_: src.models.unet3p_module.UNetLitModule
defaults:
  # - criterion: lovasz_loss.yaml
  - net: unet3plus.yaml

optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 0.0001
  weight_decay: 0.0005

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10
