_target_: src.models.yolo.yoloX_module.YoloXLitModule

defaults:
  - criterion_detect: yoloX.yaml
  - criterion_segment: lovasz_loss.yaml
  - net: YoloX.yaml

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.0001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10